W5 tests
tolya-yanot/w5 pull request #2
Opened 2024-07-03 13:52 UTC by Trinketer22

# More tests

- Improve test for internal request message length handling.
- Test case that wallet could send if deployed with signature auth disabled, but no extensions.
- Cosmetic changes like unused variables and wrapper linting.

2024-07-17 10:28 UTC, Thor45143 approved these changes

2024-08-11 20:40 UTC, Aho38wkw commented
Duplicate of #

2024-09-11 16:10 UTC, Elgayar777 approved these changes
- [ ]

2024-09-16 20:57 UTC, alijawan reviewed
1172

2024-10-12 11:39 UTC, Quest28 approved these changes

2024-10-29 22:30 UTC, alijawan requested changes

2024-10-29 22:30 UTC, alijawan commented on wrappers/wallet-v5-test.ts
> +import {
###

2024-11-22 01:44 UTC, Ferkoslav approved these changes

2024-11-22 01:46 UTC, Fart10 approved these changes
...

2024-11-27 07:22 UTC, derockspace approved these changes
Experimental wallet5

2024-12-01 02:14 UTC, USER-id811214293 commented
Pull the request procced fwd.

2024-12-04 09:51 UTC, AfeworkShalom09 approved these changes

2024-12-04 09:55 UTC, Fart10 commented on wrappers/wallet-v5-test.ts
> +import {
🙏

2024-12-04 09:55 UTC, Fart10 approved these changes
🙏

2024-12-28 00:28 UTC, 510290848 requested changes
michal pan

2025-01-12 22:00 UTC, 004sa approved these changes

2025-01-22 03:54 UTC, Feroslav268 approved these changes

2025-01-22 03:55 UTC, Feroslav268 approved these changes

2025-01-23 15:09 UTC, AfeworkShalom09 approved these changes

2025-02-14 23:41 UTC, 1987630 approved these changes

2025-02-23 03:27 UTC, Tehrani77 commented
Tehrani

2025-02-23 04:45 UTC, Ferkoslav approved these changes

2025-04-15 15:17 UTC, thuthu24 approved these changes

2025-05-05 12:00 UTC, ashishmandal-25 commented
UQCCKvPSadEGez9HmXMTo4RKDMDisQ0w5apBQUfAvsqrfvUn

2025-05-05 12:01 UTC, ashishmandal-25 commented on wrappers/wallet-v5-test.ts
> +import {
UQCCKvPSadEGez9HmXMTo4RKDMDisQ0w5apBQUfAvsqrfvUn

2025-05-08 21:36 UTC, 1987630 commented on wrappers/wallet-v5-test.ts
> +import {
```suggestion
import {
```

2025-05-15 22:16 UTC, sohiiiiiii approved these changes

2025-07-11 12:05 UTC, Amnat-auyana1998 approved these changes

2025-07-22 08:28 UTC, closed without merging